source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'Mr-Ride-iOS' do
    pod ‘Charts’
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'Alamofire', '3.4.1'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Amplitude-iOS', '~> 3.8.1'
    pod 'Google/Analytics'
end